# Generated by Django 3.1 on 2020-11-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20201128_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='image',
            field=models.FileField(blank=True, upload_to='images'),
        ),
    ]
