# Generated by Django 3.1 on 2020-11-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_todomodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
