# Generated by Django 3.1 on 2021-01-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20210113_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='duedate',
            field=models.DateField(null=True),
        ),
    ]
